# Generated by Django 4.0.1 on 2022-04-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_bids_bid_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.CharField(max_length=10),
        ),
    ]
