# Generated by Django 4.0.1 on 2022-05-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bid_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-bid',)},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='start_bid',
            new_name='price',
        ),
    ]
