# Generated by Django 4.0.1 on 2022-05-03 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listedBy',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
