# Generated by Django 4.0.1 on 2022-05-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_watchlist_alter_listing_listedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listedBy',
            field=models.CharField(max_length=20),
        ),
    ]
