# Generated by Django 4.0.1 on 2022-05-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
