# Generated by Django 4.0.1 on 2022-05-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
    ]
